### ISSUE TITLE
R-101 not work on detectron2 v0.5

### ISSUE THREAD

**Issue by lrybbs** [er-muyue/DeFRCN#10]
I'm sorry I encountered the following problem: I tried to train the network using my custom dataset, however ResNet101 doesn't work, an error is as follows:
 ERROR [11/06 15:55:17 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "d:\python_project\detectron2\detectron2\engine\train_loop.py", line 149, in train
    self.run_step()
  File "d:\python_project\detectron2\detectron2\engine\train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "D:\CodingTools\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python_project\condaproject\20211105_fs\DeFRCN-main\defrcn\modeling\meta_arch\rcnn.py", line 53, in forward
    proposal_losses, detector_losses, _, _ = self._forward_once_(batched_inputs, gt_instances)
  File "D:\python_project\condaproject\20211105_fs\DeFRCN-main\defrcn\modeling\meta_arch\rcnn.py", line 79, in _forward_once_
    proposals, proposal_losses = self.proposal_generator(images, features_de_rpn, gt_instances)
  File "D:\CodingTools\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\python_project\detectron2\detectron2\modeling\proposal_generator\rpn.py", line 477, in forward
    proposals = self.predict_proposals(
  File "d:\python_project\detectron2\detectron2\modeling\proposal_generator\rpn.py", line 503, in predict_proposals
    return find_top_rpn_proposals(
  File "d:\python_project\detectron2\detectron2\modeling\proposal_generator\proposal_utils.py", line 103, in find_top_rpn_proposals
    raise FloatingPointError(
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.
[11/06 15:55:17 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
[11/06 15:55:17 d2.utils.events]:  iter: 2  total_loss: 2.317e+23  loss_cls: 8.796e+22  loss_box_reg: 1.438e+23  loss_rpn_cls: 3.45e+15  loss_rpn_loc: 3.017e+16  data_time: 0.9142  lr: 3.998e-05  max_mem: 2848M

Obviously the value of loss function is abnormally large.
However, when I replaced the backbone with R-50, everything worked fine
May I ask what might have caused this,thanks.
By the way, I have tried using R-101 to extract the characteristics of my custom dataset on detectron2 V0.5 and it works.

**Comment by xuzhang1199** [comment]
I encountered the same problem. I am using detectron2 v0.6, and run the official code on VOC. The loss become infinite and NaN at the first iteration.

**Comment by er-muyue** [comment]
I think this problem is similar to issue #4. Please try to use the detectron0.3.
